name       : deno
version    : 1.27.2
release    : 14
source     :
    - https://github.com/denoland/deno/archive/v1.27.2.tar.gz : 796155d20335a5fd15d3c5711c1b86f57c39930541d472d00e7eb29ace4f3927
license    : MIT
component  : programming.tools
summary    : A secure JavaScript and TypeScript runtime.
description: |
    Deno is a simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust.
networking : yes
builddeps  :
    - rustup
build      : |
    rustup toolchain install stable
    cargo build --release
install    : |
    install -Dm00755 target/release/deno $installdir/usr/bin/deno
