name       : deno
version    : 1.16.0
release    : 5
source     :
    - https://github.com/denoland/deno/archive/v1.16.0.tar.gz : bceed2672021c177290a02fd2c09d139622bccc07f96bdfb0d4568aa28879b05
license    : MIT
component  : programming.tools
summary    : A secure JavaScript and TypeScript runtime.
description: |
    Deno is a simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/deno $installdir/usr/bin/deno
